defaults: &defaults
  docker:
    - image: "circleci/node:latest"

version: 2.1
jobs:
  pre-build:
    working_directory: ~/rpmgWebsite
    <<: *defaults
    steps:
      - checkout:
          path: ~/rpmgWebsite/
      - attach_workspace:
          at: ~/rpmgWebsite/

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/rpmgWebsite
          paths:
            - node_modules
  write-aws-configs:
    working_directory: ~/rpmgWebsite
    <<: *defaults
    description: |
      Configure and store AWS credentials in
      ~/.aws/credentials and ~/.aws/config
    parameters:
      aws-access-key-id:
        default: $AWS_ACCESS_KEY
        description: |
          AWS access key id for IAM role. Set this to the name of
          the environment variable you will use to hold this
          value, i.e. AWS_ACCESS_KEY.
        type: env_var_name
      aws-region:
        default: AWS_REGION
        description: |
          Env var of AWS region to operate in
          (defaults to AWS_DEFAULT_REGION)
        type: env_var_name
      aws-secret-access-key:
        default: AWS_SECRET_ACCESS_KEY
        description: |
          AWS secret key for IAM role. Set this to the name of
          the environment variable you will use to hold this
          value, i.e. $AWS_SECRET_ACCESS_KEY.
        type: env_var_name
      configure-default-region:
        default: true
        description: >
          Some AWS actions don't require a region; set this to false if you do not
          want to store a default region in ~/.aws/config
        type: boolean
      profile-name:
        default: AWS_PROFILE_NAME
        description: Profile name to be configured.
        type: string
      skip-install-check:
        default: false
        description: |
          Set to true to skip checking for existing installations before installing.
        type: boolean
      version:
        default: "2"
        description: >-
          Which version of the CLI to install. Version "1" and "2" are currently
          available. Will default to "2"
        enum:
          - "1"
          - "2"
        type: enum
    steps:
      - install:
          skip-install-check: <<parameters.skip-install-check>>
          version: <<parameters.version>>
      - run:
          command: |
            aws configure set aws_access_key_id \
              $<<parameters.aws-access-key-id>> \
              --profile <<parameters.profile-name>>
          name: Configure AWS Access Key ID
      - run:
          command: |
            aws configure set aws_secret_access_key \
              $<<parameters.aws-secret-access-key>> \
              --profile <<parameters.profile-name>>
          name: Configure AWS Secret Access Key
      - when:
          condition: <<parameters.configure-default-region>>
          steps:
            - run:
                command: |
                  aws configure set region $<<parameters.aws-region>> \
                    --profile <<parameters.profile-name>>
                name: Configure AWS default region

  gatsby-deploy:
    working_directory: ~/rpmgWebsite
    <<: *defaults
    steps:
      - checkout:
          path: ~/rpmgWebsite/
      - attach_workspace:
          at: ~/rpmgWebsite
      - run:
          command: |
            sudo apt-get -y -qq install awscli
            CI=false npm run build:ci
            aws s3 sync public/ s3://rivpsych  --region us-west-1 --delete

workflows:
  version: 2.1
  front-backend:
    jobs:
      - pre-build:
          filters:
            branches:
              only:
                - master
      - write-aws-configs:
          requires:
            - pre-build
          filters:
            branches:
              only:
                - master
      - gatsby-deploy:
          requires:
            - write-aws-configs
          filters:
            branches:
              only:
                - master
